### ISSUE TITLE
typedload.exceptions.TypedloadTypeError: Cannot deal with value of type <class 'slackclient.client.LoginInfo'>

### ISSUE THREAD

**Issue by luke-jr** [ltworf/localslackirc#281] opened 2021-03-30 00:54 UTC
Been using this for a long while, but it seems to no longer work at all. :/

```
$ python3.9 irc.py -j -c BitcoinCoreSlack.cookie -t BitcoinCoreSlack.cfg
Login in slack
Traceback (most recent call last):
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 195, in load
    index = self.index(type_)
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 185, in index
    raise ValueError('No matching condition found')
ValueError: No matching condition found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/social-sandbox/localslackirc/irc.py", line 967, in <module>
    main()
  File "/home/social-sandbox/localslackirc/irc.py", line 942, in main
    asyncio.run(irc_listener())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/social-sandbox/localslackirc/irc.py", line 903, in irc_listener
    await sl_client.login()
  File "/home/social-sandbox/localslackirc/slack.py", line 359, in login
    self.login_info = await self.client.login(15)
  File "/home/social-sandbox/localslackirc/slackclient/client.py", line 101, in login
    return load(login_data, LoginInfo)
  File "/home/social-sandbox/localslackirc/typedload/__init__.py", line 154, in load
    return loader.load(value, type_)
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 197, in load
    raise TypedloadTypeError(
typedload.exceptions.TypedloadTypeError: Cannot deal with value of type <class 'slackclient.client.LoginInfo'>
Value: {'ok': True, 'url': 'wss://cerberus-xxxx.lb.slack-msgs.com/websocket/gdwTnA3M...
Type: <class 'slackclient.client.LoginInfo'>

```

**Comment by ltworf** [comment] 2021-03-30 14:54
Did this happen after a software update or by itself?

Which versions of localslackirc and typedload are in use?

**Comment by ltworf** [comment] 2021-03-30 14:56
To debug this, a `print(login_data)` added before the load, at 

` /home/social-sandbox/localslackirc/slackclient/client.py`, line 101

would probably help.

**Comment by luke-jr** [comment] 2021-03-30 15:23
I had to update to git master (b85ae7adc50c0cbad4c0b8a09de453b30b02eb03) because the version I was using stopped working.

I don't know what typedload is. I'm running it under Python 3.9.

```
{'ok': True, 'url': 'wss://cerberus-xxxx.lb.slack-msgs.com/websocket/<some long base64>', 'team': {'id': 'T0J422BCZ', 'name': 'Bitcoin Core Community', 'domain': 'bitcoincore'}, 'self': {'id': 'U0JJWH9T7', 'name': 'luke-jr'}}
```

**Comment by ltworf** [comment] 2021-03-30 22:42
I really can't reproduce. I tried in a console to load that data and it worked.

Are you sure it's python3.9 and not 3.10?

Python 3.10 did A LOT of breaking changes on how the typing works and typedload doesn't support it yet, so on 3.10 it fails with weird messages.

**Comment by luke-jr** [comment] 2021-03-31 20:15
Yes, but my 3.9 may possibly be missing non-stock modules.

Running it in python3.8 seems to work.

**Comment by ltworf** [comment] 2021-03-31 20:28
I run it on 3.9 regularly. Do you have some non standard version with different build flags or something?

**Comment by luke-jr** [comment] 2021-03-31 20:41
Nope, looks the same for 3.8 and 3.9:

```
3.8.8(3.8)^t{tbz2}(11:37:21 PM 2021-03-14)(bluetooth gdbm hardened ipv6 ncurses readline sqlite ssl wininst xml -build -examples -libressl -test -tk -verify-sig)
3.9.2(3.9)^t{tbz2}(11:34:18 PM 2021-03-14)(bluetooth gdbm hardened ipv6 ncurses readline sqlite ssl wininst xml -build -examples -libressl -test -tk -verify-sig)
```

**Comment by ltworf** [comment] 2021-04-01 05:38
I still think you used python3.10 by mistake or somehow enabled light type evaluation to get some speedups (and break typedload)

**Comment by ltworf** [comment] 2021-04-06 17:58
https://github.com/ltworf/typedload/issues/189

**Comment by luke-jr** [comment] 2021-04-06 18:01
Again, this has nothing to do with 3.10. I don't even have 3.10 installed.

**Comment by ltworf** [comment] 2021-04-06 18:30
Well, then closing since I can't reproduce this thing.

**Comment by luke-jr** [comment] 2021-12-29 18:19
Should really remain open until fixed

Strangely, the one I was using when I reported this issue seems to be working, but a new one I'm trying to setup leads me back here...

**Comment by luke-jr** [comment] 2021-12-29 18:29
The old one is running under Python 3.8, so I guess this issue IS 3.9-specific

**Comment by ltworf** [comment] 2021-12-29 22:50
Is the stacktrace still the same?

**Comment by luke-jr** [comment] 2021-12-29 23:51
More or less, aside from line numbers which I assume are just because things have been upgraded

```
$ python3.9 irc.py -j -p 9008 -t catholic1958.cfg 
Login in slack
Traceback (most recent call last):
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 195, in load
    index = self.index(type_)
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 185, in index
    raise ValueError('No matching condition found')
ValueError: No matching condition found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/social-sandbox/localslackirc/irc.py", line 1031, in <module>
    main()
  File "/home/social-sandbox/localslackirc/irc.py", line 1006, in main
    asyncio.run(irc_listener())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/social-sandbox/localslackirc/irc.py", line 966, in irc_listener
    await sl_client.login()
  File "/home/social-sandbox/localslackirc/slack.py", line 383, in login
    self.login_info = await self.client.login(15)
  File "/home/social-sandbox/localslackirc/slackclient/client.py", line 113, in login
    return load(login_data, LoginInfo)
  File "/home/social-sandbox/localslackirc/typedload/__init__.py", line 154, in load
    return loader.load(value, type_)
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 197, in load
    raise TypedloadTypeError(
typedload.exceptions.TypedloadTypeError: Cannot deal with value of type <class 'slackclient.client.LoginInfo'>
Value: {'ok': True, 'url': 'wss://wss-primary.slack.com/websocket/jh9ejoMIlza07Q1uQU...
Type: <class 'slackclient.client.LoginInfo'>


```

**Comment by ltworf** [comment] 2022-05-26 09:12
I need to see the full value that is causing the crash.

**Comment by luke-jr** [comment] 2022-05-27 00:14
Is that sensitive information? How should I provide it?

**Comment by ltworf** [comment] 2022-05-27 08:44
Yes, but I think you can just change all the values with like XXXXX and be fine :D i just need to see the structure of the data not the tokens

**Comment by luke-jr** [comment] 2022-05-27 08:57
```{'ok': True, 'url': 'wss://wss-primary.slack.com/websocket/XXXXX/2', 'team': {'id': 'XXXXX', 'name': 'XXXXX', 'domain': 'XXXXX'}, 'self': {'id': 'XXXXX', 'name': 'XXXXX'}}

**Comment by ltworf** [comment] 2022-05-27 14:04
That string is completely normal, if I manually try to load it into the LoginInfo object it works fine

```python
In [1]: from typing import *

In [2]: from typedload import load
   ...: 

In [3]: class Team(NamedTuple):
   ...:     id: str
   ...:     name: str
   ...:     domain: str
   ...: 
   ...: 
   ...: class Self(NamedTuple):
   ...:     id: str
   ...:     name: str
   ...: 
   ...: 
   ...: class LoginInfo(NamedTuple):
   ...:     team: Team
   ...:     self: Self
   ...:     url: str
   ...: 

In [4]: load({'ok': True, 'url': 'wss://wss-primary.slack.com/websocket/XXXXX/2', 'team': {'id': 'XXXXX', 'name': 'XXXXX', 'domain': 'XXXXX'}, 'self': {'id': 'XXXXX', 'name': 'XXXXX'}}, LoginInfo)
Out[4]: LoginInfo(team=Team(id='XXXXX', name='XXXXX', domain='XXXXX'), self=Self(id='XXXXX', name='XXXXX'), url='wss://wss-primary.slack.com/websocket/XXXXX/2')
```

I really don't know what is going on here.

**Comment by luke-jr** [comment] 2022-05-27 22:18
```
>>> load({'ok': True, 'url': 'wss://wss-primary.slack.com/websocket/XXXXX/2', 'team': {'id': 'XXXXX', 'name': 'XXXXX', 'domain': 'XXXXX'}, 'self': {'id': 'XXXXX', 'name': 'XXXXX'}}, LoginInfo)
Traceback (most recent call last):
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 195, in load
    index = self.index(type_)
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 185, in index
    raise ValueError('No matching condition found')
ValueError: No matching condition found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/social-sandbox/localslackirc/typedload/__init__.py", line 154, in load
    return loader.load(value, type_)
  File "/home/social-sandbox/localslackirc/typedload/dataloader.py", line 197, in load
    raise TypedloadTypeError(
typedload.exceptions.TypedloadTypeError: Cannot deal with value of type <class '__main__.LoginInfo'>
Value: {'ok': True, 'url': 'wss://wss-primary.slack.com/websocket/XXXXX/2', 'team': {'id': 'XXXXX', 'name': 'XXXXX', 'domain': 'XXXXX'}, 'self': {'id': 'XXXXX', 'name': 'XXXXX'}}
Type: <class '__main__.LoginInfo'>
```

**Comment by ltworf** [comment] 2022-05-27 22:35
Can you tell me which versions of typedload you're running?

I see you've installed it in some very non-standard way here `/home/social-sandbox/localslackirc/typedload/__init__.py`.

I advice you to install it from your distribution or pip. I'd say you probably have some old version with some bug, or that doesn't support your newer python version, or your strange installation is corrupt somehow.

**Comment by luke-jr** [comment] 2022-05-27 23:58
Didn't realise typedload wasn't part of localslackirc. It's not available from my distro (Gentoo), so I probably just have a git cloned there

**Closed** 2022-05-28 06:11 UTC
